apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-guid-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-guid
  template:
    metadata:
      labels:
        app: nginx-guid
    spec:
      containers:
      - name: nginx-guid
        image: localhost:5000/nginx-guid:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-guid-service
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: nginx-guid       