apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginbix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginbix
  template:
    metadata:
      labels:
        app: nginbix
    spec:
      containers:
      - name: nginbix
        image: bmoshe/static-content-per-pod:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginbix-service
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: nginbix       